import { Navigation } from "./components/navigation";
import "./globals.css";
import localFont from "next/font/local";
import Logo from "./components/logo";
import { Link } from "./components/navigation/link";
import { Menu, MenuItems } from "./components/navigation/Menu";
import MenuItem from "./components/navigation/MenuItem";
import Bar from "./components/navigation/Bar";
import Backdrop from "./components/navigation/Backdrop";
import Footer from "./components/Footer";
import Button from "./components/primitives/Button";
import { ColorSchemeSelect } from "./components/ColorSchemeSelect";
import { setPersistedColorScheme } from "./components/ColorSchemeSelect/persistence";
import NextLink from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = localFont({
  src: "./inter.woff2",
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans text-zinc-700 dark:text-zinc-300`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `(${setPersistedColorScheme.toString()})()`,
          }}
        />
        <NavSection />
        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}

const links = [
  {
    href: "/",
    title: "Home",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        className="h-5 w-5"
      >
        <path
          fillRule="evenodd"
          d="M9.293 2.293a1 1 0 011.414 0l7 7A1 1 0 0117 11h-1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-3a1 1 0 00-1-1H9a1 1 0 00-1 1v3a1 1 0 01-1 1H5a1 1 0 01-1-1v-6H3a1 1 0 01-.707-1.707l7-7z"
          clipRule="evenodd"
        />
      </svg>
    ),
  },
  {
    href: "/dashboard",
    title: "Dashboard",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        className="h-5 w-5"
      >
        <path
          fillRule="evenodd"
          d="M2.5 3A1.5 1.5 0 001 4.5v4A1.5 1.5 0 002.5 10h6A1.5 1.5 0 0010 8.5v-4A1.5 1.5 0 008.5 3h-6zm11 2A1.5 1.5 0 0012 6.5v7a1.5 1.5 0 001.5 1.5h4a1.5 1.5 0 001.5-1.5v-7A1.5 1.5 0 0017.5 5h-4zm-10 7A1.5 1.5 0 002 13.5v2A1.5 1.5 0 003.5 17h6a1.5 1.5 0 001.5-1.5v-2A1.5 1.5 0 009.5 12h-6z"
          clipRule="evenodd"
        />
      </svg>
    ),
  },
];

const NavSection = () => {
  return (
    <>
      <Navigation links={links}>
        <div className="px-6 pb-1 pt-10 backdrop-blur backdrop-saturate-150">
          <Bar
            logo={
              <NextLink href="/">
                <Logo
                  className="animate-logo h-10 text-black dark:text-white"
                  strokeWidth={1}
                />
              </NextLink>
            }
          />
        </div>
        <Menu>
          <MenuItems>
            {links.map(({ title, href, icon }) => (
              <MenuItem key={title}>
                <Link href={href} title={title} icon={icon} />
              </MenuItem>
            ))}
          </MenuItems>

          <div className="m-2 flex items-end gap-8 md:hidden">
            <Button style={{ flex: 2 }}>
              <span className="flex w-full items-center justify-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  className="h-5 w-5"
                >
                  <path d="M10.75 2.75a.75.75 0 00-1.5 0v8.614L6.295 8.235a.75.75 0 10-1.09 1.03l4.25 4.5a.75.75 0 001.09 0l4.25-4.5a.75.75 0 00-1.09-1.03l-2.955 3.129V2.75z" />
                  <path d="M3.5 12.75a.75.75 0 00-1.5 0v2.5A2.75 2.75 0 004.75 18h10.5A2.75 2.75 0 0018 15.25v-2.5a.75.75 0 00-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5z" />
                </svg>
                <span>Download resume</span>
              </span>
            </Button>
            <div>
              <div className="w-full flex-1">
                <ColorSchemeSelect />
              </div>
            </div>
          </div>
        </Menu>

        <Backdrop />
      </Navigation>
      {/* <section className="max-w-5xl flex justify-between items-center mx-auto"> */}
      {/* <div>
          <Logo className="h-10" strokeWidth={1.15} />
        </div> */}
      {/* <div className="hidden items-center gap-12 lg:inline-flex">
        <Navigation
          links={[
            { href: "/", title: "Home" },
            { href: "/dashboard", title: "Dashboard" },
          ]}
        />
        <button className="rounded-xl bg-foxfire-400 px-4 py-2 text-black shadow-foxfire-800 transition-shadow hover:shadow-md">
          <span className="inline-flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="h-5 w-5"
            >
              <path d="M10.75 2.75a.75.75 0 00-1.5 0v8.614L6.295 8.235a.75.75 0 10-1.09 1.03l4.25 4.5a.75.75 0 001.09 0l4.25-4.5a.75.75 0 00-1.09-1.03l-2.955 3.129V2.75z" />
              <path d="M3.5 12.75a.75.75 0 00-1.5 0v2.5A2.75 2.75 0 004.75 18h10.5A2.75 2.75 0 0018 15.25v-2.5a.75.75 0 00-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5z" />
            </svg>
            <span>Download resume</span>
          </span>
        </button>
      </div> */}
      {/* </section> */}
    </>
  );
};
